title: Blog Bibliotheks- und Archivinformatik
author: Sarah Röllin
email: sarah.roellin@gmail.com
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS2021

# social links
github_username:  SarahR177

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
